{{- $host := pluck .Values.global.env .Values.host | first | default .Values.host._default  }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{- if eq .Values.global.env "production" }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
{{- end }}
{{- if ne .Values.global.env "production" }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
{{- end }}
spec:
  tls:
  - hosts:
      - {{ $host }}
      - ru.{{ $host }}
{{- if eq .Values.global.env "production" }}
      - www.{{ $host }}
{{- end }}
    secretName: tls-{{ $host }}
  rules:
  - host: {{ $host }}
    http:
      paths:
{{- if eq .Values.global.env "production" }}
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80
{{- else }}
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-dev
          servicePort: 80
      - path: /v
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80
{{- end }}
  - host: ru.{{ $host }}
    http:
      paths:
{{- if eq .Values.global.env "production" }}
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80
{{- else }}
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-dev
          servicePort: 80
      - path: /v
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80
{{- end }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-cert
spec:
  secretName: tls-{{ $host }}
  issuerRef:
    kind: ClusterIssuer
{{- if eq .Values.global.env "production" }}
    name: letsencrypt
{{- else }}
    name: letsencrypt-staging
{{- end }}
  commonName: {{ $host }}
  dnsNames:
  - {{ $host }}
  - ru.{{ $host }}
{{- if eq .Values.global.env "production" }}
  - www.{{ $host }}
{{- end }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ $host }}
      - ru.{{ $host }}
{{- if eq .Values.global.env "production" }}
      - www.{{ $host }}
{{- end }}
