---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost_exporter
spec:
  replicas: {{ pluck .Values.global.env .Values.replicas | first | default .Values.replicas._default }}
  selector:
    matchLabels:
      app: cost_exporter
  template:
    metadata:
      labels:
        app: cost_exporter
    spec:
      imagePullSecrets:
      containers:
      - name: cost_exporter
        image: nachomillangarcia/prometheus_aws_cost_exporter:latest
        args:
        - --host
        - 0.0.0.0
        ports:
        - name: http-metrics
          containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "{{ .Values.aws_access_key_id }}"
        - name: AWS_SECRET_ACCESS_KEY
          value: "{{ .Values.aws_secret_access_key }}"
        - name: METRIC_TODAY_DAILY_COSTS
          value: "{{ .Values.env.metric_today_daily_costs }}"
        - name: METRIC_YESTERDAY_DAILY_COSTS
          value: "{{ .Values.env.metric_yesterday_daily_costs }}"
        - name: QUERY_PERIOD
          value: "{{ .Values.env.query_period }}"
        - name: METRIC_TODAY_DAILY_USAGE
          value: "{{ .Values.env.metric_today_daily_usage }}"
        - name: METRIC_TODAY_DAILY_USAGE_NORM
          value: "{{ .Values.env.metric_today_daily_usage_norm }}"
        resources:
          requests:
            cpu: {{ pluck .Values.global.env .Values.resources.requests.cpu | first | default .Values.resources.requests.cpu._default }}
            memory: {{ pluck .Values.global.env .Values.resources.requests.memory | first | default .Values.resources.requests.memory._default }}
          limits:
            memory: {{ pluck .Values.global.env .Values.resources.requests.memory | first | default .Values.resources.requests.memory._default }}
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
